### ISSUE TITLE
Cant find grbl ros package

### ISSUE THREAD

**Issue by yagizzha** [flynneva/grbl_ros#108]
![image](https://user-images.githubusercontent.com/88779645/139411465-2a1a2aae-77da-45f5-8eb7-ef64245e99e4.png)

After compiling when i try to use "ros2 run grbl_ros grbl_node --ros-args --params-file /path/to/workspace/src/grbl_ros/config/cnc001.yaml", it says "Package 'grbl_ros' not found" even though i have it installed.

**Comment by yagizzha** [comment]
> @yagizzha after compiling make sure to run `source install/setup.bash` from your `colcon_ws`

Thanks for that but now im having another problem : 
![image](https://user-images.githubusercontent.com/88779645/140035989-e51e0733-8174-4c48-8b13-463f5b6376f8.png)
i have the file there and inside of it is filled but arguments still cant be parsed

**Comment by flynneva** [comment]
@yagizzha could you make a new issue with your new problem? I am looking into it to see if I can reproduce it and will reply back on that new issue.
