### ISSUE TITLE
failed to parse global arguments

### ISSUE THREAD

**Issue by yagizzha** [flynneva/grbl_ros#109]
![image](https://user-images.githubusercontent.com/88779645/141757914-0efd2fd9-81ed-49f6-9595-fc09696ae282.png)

i get this error when i try to : ros2 run grbl_ros grbl_node --ros-args --params-file /path/to/workspace/src/grbl_ros/config/cnc001.yaml

**Comment by flynneva** [comment]
@yagizzha this error looks like it might be caused by your yaml file having a typo in it.

Could you share your yaml file? Fill it in with fake / dummy data if you'd like but keep the formatting the same.

**Comment by yagizzha** [comment]
/**:
  ros__parameters:
    machine_id: cnc_001
    port: /dev/ttyUSB0
    baudrate: 115200
    x_max: 300  # mm
    y_max: 200  # mm
    z_max: 150  # mm
    default_v: 100  # mm / min
    x_max_v: 150  # mm / min
    y_max_v: 150  # mm / min
    z_max_v: 150  # mm / min
    x_steps: 100  # steps / mm
    y_steps: 100  # steps / mm
    z_steps: 100  # steps / mm

**Comment by yagizzha** [comment]
didnt change anything in it

**Comment by flynneva** [comment]
It has to be the path to where the yaml file is in your system

**Comment by flynneva** [comment]
@yagizzha was your issue fixed? are you still seeing the same problem?

**Comment by yagizzha** [comment]
![image](https://user-images.githubusercontent.com/88779645/141935474-f5170433-1a06-45e3-a54c-a0c800839d1e.png)
solved one problem but now i get this , do i need to have a working grbl device to start it ?
