### ISSUE TITLE
Index error 

### ISSUE THREAD

**Issue by yagizzha** [flynneva/grbl_ros#110]
![image](https://user-images.githubusercontent.com/88779645/142992001-e11db992-1d2c-450f-b83d-c89fb57536e2.png)

grbl device is working on arduino , serial monitor shows its responding as expected but on ROS2 side it doesnt work

**Comment by flynneva** [comment]
hi @yagizzha! thanks for using this package, and thanks even more for reporting issues you do find!

I've [tried to implement a fix for this error](https://github.com/flynneva/grbl_ros/commit/074bcc5f21ec2d385f76ddbc2ca3af5b7b184dac) by warning the user if a received status is missing the required fields.

Could you try out that branch and let me know if it fixes your problem...or at least points you in the right direction?
